provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  url-ping:
    lang: python3
    handler: ./url-ping
    image: url-ping

# Add new line to trigger build
  url-ping-js:
    lang: node
    handler: ./url-ping-js
    image: url-ping-js
  url-ping-go:
    lang: go
    handler: ./url-ping-go
    image: url-ping-go
  url-ping-ruby:
    lang: ruby
    handler: ./url-ping-ruby
    image: url-ping-ruby
